"""create initial schema

Revision ID: 1e6a811cfa8a
Revises: bfe064496dd2
Create Date: 2026-05-27 07:49:55.487435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1e6a811cfa8a'
down_revision: Union[str, None] = 'bfe064496dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###